import math 

# Math module methods
# Math module includes various arithmetical subjects and operators
print("e")
print(math.e)
print("inf")
print(math.inf)
print("nan")
print(math.nan)
print("pi")
print(math.pi)
print("tau")
print(math.tau)
# All numbers input
print("tan")
print(math.tan(90))
print("tanh")
print(math.tanh(90))
print("atan")
print(math.atan(90))
print("atan2")
print(math.atan2(1, 1))
print("sinh")
print(math.sinh(60))
print("asinh")
print(math.asinh(60))
print("cosh")
print(math.cosh(30))
print("erf")
print(math.erf(5))
print("erfc")
print(math.erfc(5))
print("fmod")
print(math.fmod(11, 6))
print("exp")
print(math.exp(5))
print("expm1")
print(math.expm1(5))
print("frexp")
print(math.frexp(5))
print("ldexp")
print(math.ldexp(1.25, 2))
print("ceil")
print(math.ceil(4.4))
print("trunc")
print(math.trunc(5.4))
print("floor")
print(math.floor(5.6))
print("comb")
print(math.comb(5, 4))
print("perm")
print(math.perm(5, 4))
print("factorial")
print(math.factorial(5))
print("pow")
print(math.pow(5 ** (1 / 2), 2))
print("sqrt")
print(math.sqrt(25))
print("gcd")
print(math.gcd(15, 25))
print("remainder")
print(math.remainder(5, 4))
print("copysign")
print(math.copysign(-5, 2))
print("fabs")
print(math.fabs(-5))
print("isclose")
print(math.isclose(1.25, 1.251))
print("isfinite")
print(math.isfinite(0))
print("isinf")
print(math.isinf(1))
print("isnan")
print(math.isnan(1))
# W numbers input
print("gamma")
print(math.gamma(5))
print("lgamma")
print(math.lgamma(5))
print("isqrt")
print(math.isqrt(26))
print("log")
print(math.log(1))
print("log10")
print(math.log10(100000))
print("log1p")
print(math.log1p(0))
print("log2")
print(math.log2(1))
# W - (1 , 0) numbers input
print("acosh")
print(math.acosh(1))
# [-1 , +1] numbers input
print("acos")
print(math.acos(-1))
print("asin")
print(math.asin(1))
print("cos")
print(math.cos(0))
print("sin")
print(math.sin(0))
# (-1 , +1) numbers input
print("atanh")
print(math.atanh(0.5))
# Angles input
print("degrees")
print(math.degrees(math.pi))
print("radians")
print(math.radians(90))
# Coordinated points input
print("dist")
print(math.dist((3, 4), (0, 0)))
print("hypot")
print(math.hypot(3, 4))
# Arrays input
print("fsum")
print(math.fsum((1, 2, 2)))
print("prod")
print(math.prod([1, 2, 2]))

