import platform

# Platform module methods
# Platform module includes Your device's specs information
print("processor")
print(platform.processor())
print("version")
print(platform.version())
print("machine")
print(platform.machine())
print("node")
print(platform.node())
print("platform")
print(platform.platform())
print("system")
print(platform.system())
print("release")
print(platform.release())
print("uname")
print(platform.uname())
print("win32_edition")
print(platform.win32_edition())
print("win32_is_iot")
print(platform.win32_is_iot())
print("win32_ver")
print(platform.win32_ver())
print("java_ver")
print(platform.java_ver())
print("mac_ver")
print(platform.mac_ver())
print("python_build")
print(platform.python_build())
print("python_branch")
print(platform.python_branch())
print("python_compiler")
print(platform.python_compiler())
print("python_implementation")
print(platform.python_implementation())
print("python_revision")
print(platform.python_revision())
print("python_version")
print(platform.python_version())
print("python_version_tuple")
print(platform.python_version_tuple())
platform.architecture()
platform.uname_result
platform.freedesktop_os_release
platform.system_alias
platform.__builtins__
platform.__cached__
platform.__file__
platform.__name__
platform.__version__
platform.__doc__
platform.__loader__
platform.__package__
platform.__spec__